config/routes.rb
TeacherDucklings::Application.routes.draw do
  resources :links, :users, :meetings, :videos
  resources :categories, only: :show

  resources :posts, only: [:index, :show] do
    resources :comments
  end
  
  resources :user_sessions
  resources :password_resets
  match '/login'  => 'user_sessions#new'
  match '/logout' => 'user_sessions#destroy'

  namespace :admin do
    resources :links, :categories, :meetings, :users

    resources :posts do
      resources :comments
    end

    resources :videos do
      resources :reviews
    end

    root to: 'dashboard#index'
  end

  root to: 'index#index'
end

app/models/meeting.rb
require 'opentok'

class Meeting < ActiveRecord::Base
  belongs_to :video
  belongs_to :moderator, foreign_key: 'creator_id', class_name: 'User'
  belongs_to :user,      foreign_key: 'user_to_meet_with_id'
    
  validates :date,       presence: true
  validates :time,       presence: true
  validates :video,      presence: true
  validates :moderator,  presence: true
  validates :user,       presence: true

  default_scope includes(:video, :moderator, :user).order('date ASC')
  scope :for_user, lambda { |user| where(user_to_meet_with_id: user) }
  scope :for_moderator, lambda { |mod| where(creator_id: mod) }

  def self.find_upcoming_meetings
    now      = Date.today
    upcoming = now + 7

    where("date >= :start_date AND date < :end_date",
          { start_date: now, end_date: upcoming }) 
  end
  
  def days_from_today_to_meeting
    (date - Date.today).to_i
  end
  
  def expired?
    date < Date.today
  end

  def set_tok_session_id(addr)
    open_tok = OpenTok::OpenTokSDK.new ENV['TOKBOX_API_KEY'], ENV['TOKBOX_API_SECRET']
    session = open_tok.create_session(addr)
    self.tok_session_id = session.session_id
  end
  
end

app/controllers/admin/meetings_controller.rb
class Admin::MeetingsController < AdminController
  rescue_from ActiveRecord::RecordNotFound, with: :meeting_not_found

  def index
    @meetings = Meeting.all
    @date = params[:month] ? Date.parse(params[:month]) : Date.today
  end

  def new
    @meeting = Meeting.new
    @admins = User.admins
    @users = User.all
  end

  def edit
    @meeting = Meeting.find(params[:id])
    @admins = User.admins
    @users = User.all
  end

  def create
    @meeting = Meeting.new(params[:meeting])
    @meeting.set_tok_session_id request.remote_addr

    if @meeting.save
      flash[:success] = 'Meeting was successfully scheduled.'
      redirect_to admin_meetings_path
    else
      render action: 'new'
    end
  end

  def update
    @meeting = Meeting.find(params[:id])
    @meeting.set_tok_session_id request.remote_addr

    if @meeting.update_attributes(params[:meeting])
      flash[:success] = 'Meeting was successfully updated.'
      redirect_to admin_meetings_path
    else
      render action: 'edit'
    end
  end

  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    flash[:notice] = "Meeting was successfully deleted."
    redirect_to admin_meetings_path
  end
  
  
  protected
  
  def meeting_not_found
    flash[:error] = 'Sorry, but that meeting could not be found.'
    redirect_to admin_meetings_path
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_filter :assign_categories
  before_filter :login_required
  
  def index
    find_recent_posts
    @meetings = Meeting.for_user(current_user)
  end
  
  def show
    @meeting = Meeting.find(params[:id])
    unless (@meeting.user_to_meet_with_id.to_i == current_user.id) || current_user.admin
      flash[:error] = "Sorry, but you're not scheduled to attend this meeting."
      redirect_to root_path
    else
      @token = current_user.generate_tok_token(@meeting.tok_session_id)
      @video = @meeting.video
      render :layout => 'meeting'
    end
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Sorry, but that meeting could not be found.'
    redirect_to meetings_path
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/admin/meetings/_form.html.erb
<%= f.input :date, as: :string, input_html: { size: 40, class: 'datepicker' } %>
<%= f.input :time, input_html: { size: 40 } %>
<%= f.association :moderator, collection: @admins, label_method: 'full_name', include_blank: false %>
<%= f.association :user, label: 'Meet with', collection: @users, label_method: 'full_name', include_blank: false %>
<%= f.association :video, label_method: 'verbose_title', include_blank: false %>
<%= f.input :confirmed, as: :boolean %>

app/views/admin/meetings/_meeting.html.erb
<div class="resource-row <%= cycle 'odd', 'even' %>">
	<div style="float: right;">
		<br />
		<%= link_to 'Go to Meeting', admin_meeting_path(meeting), :class => 'show' %>
    <%= link_to 'Edit', edit_admin_meeting_path(meeting), :class => 'edit' %>
    <%= link_to 'Cancel', admin_meeting_path(meeting), :confirm => 'Are you sure?', :method => :delete, :class => 'delete' %>
	</div>
	<strong>Date:</strong> <%= meeting.date %> @ <%= meeting.time %><br />
	<strong>User:</strong> <%= meeting.video.user.full_name %>, 
	<strong>Video:</strong> <%= link_to meeting.video.verbose_title, admin_video_path(meeting.video) %><br />
	<strong>Confirmed:</strong> <%= meeting.confirmed %>
</div>
<div class="clear"></div>

app/views/admin/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= simple_form_for @meeting, url: admin_meeting_path(@meeting) do |f| %>
  <fieldset>
    <%= render 'form', f: f %>
  </fieldset>

  <div class="form-actions">
    <%= f.button :submit, 'Update meeting', class: 'btn btn-primary' %>
    <%= link_to 'Cancel', :back, class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/admin/meetings/index.html.erb
<h1>All Meetings</h1>

<%= link_to 'New meeting', new_admin_meeting_path, class: 'btn btn-success btn-large' %>

<div id="calendar">
  <h2 id="month">
    <%= link_to "< previous", :month => (@date.beginning_of_month-1).strftime("%Y-%m-01") %>
    <%=h @date.strftime("%B %Y") %>
    <%= link_to " next >", :month => (@date.end_of_month+1).strftime("%Y-%m-01") %>
  </h2>

  <%= calendar_for @meetings, :year => @date.year, :month => @date.month do |calendar| %>
    <%= calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday') %>
    <% calendar.day(:day_method => :date) do |date, meetings| %>
      <%= date.day %>
      <ul>
        <% meetings.each do |meeting| %>
          <li>
            <%= link_to "#{meeting.time} - #{meeting.user.full_name}", 
                meeting_path(meeting), 
                class: 'has-tip', 
                title: "#{meeting.moderator.full_name} meeting with #{meeting.user.full_name} at #{meeting.time}" 
            %>
          </li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>

app/views/admin/meetings/new.html.erb
<h1>New Meeting</h1>

<%= simple_form_for @meeting, url: admin_meetings_path do |f| %>
  <fieldset>
    <%= render 'form', f: f %>
  </fieldset>

  <div class="form-actions">
    <%= f.button :submit, 'Create meeting', class: 'btn btn-primary' %>
    <%= link_to 'Cancel', :back, class: 'btn btn-danger' %>
  </div>
<% end %>