config/routes.rb
TeacherDucklings::Application.routes.draw do
  resources :links, :users, :meetings, :videos
  resources :categories, only: :show

  resources :posts, only: [:index, :show] do
    resources :comments
  end
  
  resources :user_sessions
  resources :password_resets
  match '/login'  => 'user_sessions#new'
  match '/logout' => 'user_sessions#destroy'

  namespace :admin do
    resources :links, :categories, :meetings, :users

    resources :posts do
      resources :comments
    end

    resources :videos do
      resources :reviews
    end

    root to: 'dashboard#index'
  end

  root to: 'index#index'
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < AdminController
  rescue_from ActiveRecord::RecordNotFound, with: :review_not_found
  before_filter :load_video

  def edit
    @review = @video.reviews.find(params[:id])
  end

  def create
    @review_params = params[:review].merge(user_id: current_user.id)
    @review = @video.reviews.new(@review_params)
    
    if @review.save
      flash[:success] = 'Your review was successfully recorded.'
      redirect_to admin_video_path(@video)
    else
      flash[:error] = 'Your review could not be saved. Please make sure all required fields are filled-in, and try again.'
      redirect_to admin_video_path(@video)
    end
  end

  def update
    @review = @video.reviews.find(params[:id])

    if @review.update_attributes(params[:review])
      flash[:success] = 'Your review was successfully updated.'
      redirect_to admin_video_path(@video)
    else
      render action: 'edit'
    end
  end

  def destroy
    @review = @video.reviews.find(params[:id])
    @review.destroy
    
    redirect_to admin_video_path(@video), notice: 'Your review was successfully deleted.'
  end
  
  
  protected
  
  def load_video
    @video = Video.find(params[:video_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to admin_videos_path, notice: 'Sorry, but we cannot find that video.'
  end
  
  def review_not_found
    redirect_to admin_video_path(@video), notice: 'Sorry, but we cannot find that review.'
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/reviews/_review.html.erb
<%= div_for review do %>
  <div class="info">
    <h4>Reviewed by: <%= review.user.full_name %></h4>
    <span class="time"><%= time_ago_in_words(review.updated_at) %> ago.</span>
  </div>

  <div class="attachment">
    <% if review.pdf.present? %>
      <%= link_to image_tag('icons/pdf_48.png'), review.pdf.url %>
    <% end %>
  </div>

  <div class="description">
    <strong>Description: </strong><%= review.description %>
  </div>

  <div class="actions">
    <%= link_to 'Edit review', edit_admin_video_review_path(@video, review), class: 'edit' %>
    <%= link_to 'Delete review', admin_video_review_path(@video, review), method: :delete,
      confirm: 'Are you sure you want to delete this review?', class: 'delete' %>
  </div>
  <div class="clear"></div>
<% end %>

app/views/admin/reviews/edit.html.erb
<h1>Update Your Review</h1>

<%= simple_form_for @review, url: admin_video_review_path(@video, @review), html: { multipart: true, class: 'form-vertical' } do |f| %>
  <fieldset>
    <%= f.input :description, input_html: { rows: 5 } %>
    <% if @review.pdf.present? %>
      <%= f.input :pdf, as: :string, disabled: true, value: @review.pdf_file_name,
        hint: 'File already attached' %>
    <% else %>
      <%= f.input :pdf, as: :file, label: 'Attach a PDF', required: false %>
    <% end %>
  </fieldset>

  <div class="form-actions">
    <%= f.button :submit, 'Update review', class: 'btn btn-primary' %>
    <%= link_to 'Cancel', :back, class: 'btn btn-danger' %>
  </div>
<% end %>