config/routes.rb
TeacherDucklings::Application.routes.draw do
  resources :links, :users, :meetings, :videos
  resources :categories, only: :show

  resources :posts, only: [:index, :show] do
    resources :comments
  end
  
  resources :user_sessions
  resources :password_resets
  match '/login'  => 'user_sessions#new'
  match '/logout' => 'user_sessions#destroy'

  namespace :admin do
    resources :links, :categories, :meetings, :users

    resources :posts do
      resources :comments
    end

    resources :videos do
      resources :reviews
    end

    root to: 'dashboard#index'
  end

  root to: 'index#index'
end

app/models/user.rb
require 'opentok'

class User < ActiveRecord::Base
  include Permissions
  
  default_scope order: :last_name
  scope :admins, where(admin: true)
  
  acts_as_authentic
  
  has_many :videos, :dependent => :destroy
  has_many :posts, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :reviews, :dependent => :destroy
  has_many :meetings, :dependent => :destroy, :foreign_key => "creator_id"

  has_attached_file :photo,
    :storage => :s3,
    :bucket => ENV['S3_BUCKET'],
    :s3_credentials => {
      :access_key_id => ENV['S3_KEY'],
      :secret_access_key => ENV['S3_SECRET']
    },
    :url => '/photos/:id/:basename.:extension',
    :path => '/photos/:id/:basename.:extension'

  validates_presence_of :first_name, :last_name, :email
  
  def full_name
    [first_name, last_name].join(" ")
  end
  alias_method :name, :full_name
  
  def deliver_password_reset_instructions!
    reset_perishable_token!
    UserMailer.password_reset_instructions(self).deliver
  end
  
  def user
    self
  end

  def generate_tok_token(session_id)
    open_tok = OpenTok::OpenTokSDK.new ENV['TOKBOX_API_KEY'], ENV['TOKBOX_API_SECRET']
    open_tok.generate_token(:session_id => session_id, :connection_data => "name=#{full_name}")
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  rescue_from ActiveRecord::RecordNotFound, with: :user_not_found
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    
    if @user.save
      flash[:success] = 'New user was successfully created.'
      redirect_to admin_users_path
    else
      render action: 'new'
    end
  end
  
  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      flash[:success] = 'User was successfully updated.'
      redirect_to admin_users_path
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: 'User was successfully deleted.'
  end
  
  
  protected
  
  def user_not_found
    redirect_to admin_users_path, notice: 'Sorry, but that user could not be found.'
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required
  before_filter :assign_categories
  before_filter :find_recent_posts
  before_filter :load_user

  def show
  end
  
  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = 'User profile successfully updated.'
      redirect_to @user
    else
      render action: 'edit'
    end
  end
  
  
  protected
  
  def load_user
    @user = current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/views/admin/users/_form.html.erb
<%= f.input :first_name, input_html: { size: 40 } %>
<%= f.input :last_name, input_html: { size: 40 } %>
<%= f.input :phone_number, required: false, input_html: { size: 40 } %>
<%= f.input :email, input_html: { size: 40 } %>
<%= f.input :password, required: false, hint: 'Only update if you want to change your password.' %>
<%= f.input :password_confirmation, required: false %>
<%= f.input :photo, as: :file, required: false %>
<%= f.input :admin, as: :boolean, value: false, label: 'Administrator?', required: false %>

app/views/admin/users/_user.html.erb
<div class="resource-row <%= cycle 'odd', 'even' %>">
  <%= div_for user do %>
    <div class="name">
      <h4><%= user.full_name %> - Videos(<%= user.videos.size %>)</h4>
    </div>

    <div class="pic">
      <%= image_tag user.photo.url(:small) %>
    </div>

    <div class="contact-info">
      <div class="phone">
        <strong>Phone Number: </strong><%= user.phone_number %>
      </div>
      <div class="email">
        <strong>Email Address: </strong><%= user.email %>
      </div>
      <div class="admin">
        <strong>Administrator: </strong><%= user.admin? %>
      </div>
    </div>

    <div class="actions">
      <%= link_to 'Show', admin_user_path(user), class: 'show' %>
      <%= link_to 'Edit', edit_admin_user_path(user), class: 'edit' %>
      <%= link_to 'Destroy', admin_user_path(user), 
        confirm: 'Are you sure you want to delete this user? All of their posts, comments, and videos will be deleted with them.', 
        method: :delete, class: 'delete' 
      %>
	</div>
    <div class="clear"></div>
  <% end %>
</div>

app/views/admin/users/edit.html.erb
<h1>Edit User</h1>

<%= simple_form_for @user, url: admin_user_path(@user), html: { multipart: true, class: 'form-vertical' } do |f| %>
  <fieldset>
    <legend>User details</legend>
    <%= render 'form', f: f %>
  </fieldset>

  <div class="form-actions">
    <%= f.button :submit, 'Update user', class: 'btn btn-primary' %>
    <%= link_to 'Cancel', :back, class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<h1>User Administration</h1>

<%= link_to "New user", new_admin_user_path, class: 'btn btn-success btn-large' %>

<div id="users">
  <%= render @users %>
</div>

app/views/admin/users/new.html.erb
<h1>Create New User</h1>

<%= simple_form_for @user, url: admin_users_path, html: { multipart: true, class: 'form-vertical' } do |f| %>
  <fieldset>
    <legend>User details</legend>
    <%= render 'form', f: f %>
  </fieldset>

  <div class="form-actions">
    <%= f.button :submit, 'Save user', class: 'btn btn-primary' %>
    <%= link_to 'Cancel', :back, class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/admin/users/show.html.erb
<div class="profile-pic">
	<%= image_tag @user.photo.url(:medium) %>
</div>

<div class="float-left">
	<h1><%= @user.full_name %></h1>

	<p>
		<strong>Phone Number: </strong><%= @user.phone_number %><br />
		<strong>Email: </strong><%= @user.email %>
	</p>
</div>
<div class="clear"></div>

<p class="edit"><%= link_to "Edit user", edit_admin_user_path(@user) %></p>

<h2>Videos (<%= @user.videos.size %>)</h2>
<%= render @user.videos %>