config/routes.rb
TeacherDucklings::Application.routes.draw do
  resources :links, :users, :meetings, :videos
  resources :categories, only: :show

  resources :posts, only: [:index, :show] do
    resources :comments
  end
  
  resources :user_sessions
  resources :password_resets
  match '/login'  => 'user_sessions#new'
  match '/logout' => 'user_sessions#destroy'

  namespace :admin do
    resources :links, :categories, :meetings, :users

    resources :posts do
      resources :comments
    end

    resources :videos do
      resources :reviews
    end

    root to: 'dashboard#index'
  end

  root to: 'index#index'
end

app/models/video.rb
class Video < ActiveRecord::Base
  include Permissions
  
  belongs_to :user
  has_many :meetings, dependent: :destroy
  has_many :reviews,  dependent: :destroy
  
  validates :user,            presence: true
  validates :title,           presence: true
  validates :video_file_name, presence: true

  default_scope :order => "created_at DESC"

  before_destroy :delete_files_from_s3
  
  def self.find_recent_uploads
    time = Date.today - 7.days
    find(:all, :conditions => [ 'created_at > ?', time ], :order => 'created_at DESC' )
  end

  # State machine
  state_machine :initial => :uploaded do
    event :convert do
      transition all => :converting
    end
    
    event :complete do
      transition any => :complete
    end
    
    event :error do
      transition any => :error
    end
  end 
  
  def verbose_title
    "#{title} - #{video_file_name}"
  end

  def encoded_file_name
    "https://#{ENV['S3_BUCKET']}.s3.amazonaws.com/#{video_file_name}.mp4"
  end
  
  def encode!
    convert!
    encoder = VideoEncoder.new(self)
    job_id = encoder.create_job
    update_attributes(zencoder_job_id: job_id)
  rescue VideoEncoder::EncodingError => e
    encoding_error! e.message
  end

  def check_encoding_status
    return state unless converting?
    result = VideoEncoder.check_job_status(zencoder_job_id)

    case result[:status]
    when 'complete'
      complete!
    when 'converting'
      convert!
    when 'error'
      encoding_error!(result[:message])
    end
    state
  end


  private

  def encoding_error!(message)
    update_attributes(zencoder_error_message: message)
    error!
  end

  def delete_files_from_s3
    aws           = AWS::S3.new(access_key_id: ENV['S3_KEY'], secret_access_key: ENV['S3_SECRET'])
    bucket        = aws.buckets[ENV['S3_BUCKET']]
    video         = bucket.objects[video_file_name]
    encoded_video = bucket.objects["#{video_file_name}.mp4"]

    video.delete
    encoded_video.delete
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < AdminController
  rescue_from ActiveRecord::RecordNotFound, with: :video_not_found

  def index
    @videos = Video.all
  end

  def show
    @video = Video.find(params[:id])
    @video.check_encoding_status
  end
  
  def new
    @video = current_user.videos.new
    render template: 'shared/videos/new'
  end

  def create
    @video = current_user.videos.new(params[:video])

    if @video.save
      @video.encode!
      flash[:success] = 'Video successfully created.'
      redirect_to admin_videos_path
    else
      render template: 'shared/videos/new'
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to admin_videos_path, notice: 'Video successfully deleted.'
  end

  
  protected
  
  def video_not_found
    redirect_to admin_videos_path, notice: 'Sorry, but that video could not be found.'
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :login_required
  before_filter :assign_categories
  before_filter :find_recent_posts
  
  def index
    @videos = current_user.videos
  end

  def show
    @video = current_user.videos.find(params[:id])
    @video.check_encoding_status
  rescue ActiveRecord::RecordNotFound
    flash[:error] = "We're sorry, but the video you're looking for cannot be found."
    redirect_to videos_path
  end

  def new
    @video = current_user.videos.new
    render template: 'shared/videos/new'
  end

  def create
    @video = current_user.videos.create(params[:video])
    if @video.save
      @video.encode!
      redirect_to videos_path, notice: 'Video successfully uploaded. Please give it a few minutes to encode.'
    else
      render template: 'shared/videos/new'
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/admin/videos/_video.html.erb
<div class="resource-row <%= cycle 'odd', 'even' %>">
  <%= div_for video do %>
    <div class="title">
      <h4><%= video.title %></h4>
    </div>
    <div class="clear"></div>

    <div class="image">
      <%= image_tag 'movie.png' %>
    </div>

    <div class="info">
      <div class="user">
        <strong>User: </strong><%= link_to video.user.full_name, admin_user_path(video.user) %>
      </div>
      <div class="state">
        <strong>Status: </strong><%= video.state.camelize %>
      </div>
      <div class="date">
        <strong>Created: </strong><%= time_ago_in_words video.created_at %> ago
      </div>
    </div>

    <div class="actions">
      <%= link_to 'Watch', admin_video_path(video), class: 'show' %>
	  <%= link_to 'Delete', admin_video_path(video), confirm: 'Are you sure?', method: :delete, class: 'delete' %>
    </div>
  <% end %>
  <div class="clear"></div>
</div>

app/views/admin/videos/index.html.erb
<h1>All Videos</h1>

<%= link_to 'New video', new_admin_video_path, :class => 'btn btn-success btn-large' %>

<div id="videos">
  <%= render @videos %>
</div>

app/views/admin/videos/new.html.erb
<%= content_for :javascript do %>
  <%= javascript_include_tag 'admin/swfobject' %>
  <%= s3_upload_script({ key: 'video', button_text: 'Choose video file' }).html_safe %>
<% end %>


<h1>New video</h1>

<%= simple_form_for @video, url: admin_videos_path do |f| %>
  <fieldset>
    <legend>Video details</legend>
    <div class='control-group'>
      <%= link_to 'Choose video file', '#', id: 'upload_video', class: 'btn' %>
      <div id="instructions" class="alert alert-success" style="display: none;">
        Now please complete the form and save.
      </div>
    </div>

    <%= render 'form', f: f %>
  </fieldset>

  <div class="form-actions">
    <%= f.button :submit, 'Save video', class: 'btn btn-primary' %>
    Please wait for the video to finish uploading before hitting 'Save video.'
  </div>
<% end %>

app/views/admin/videos/show.html.erb
<%= div_for @video do %>
  <div class="title">
    <h2><%= @video.title %></h2>
  </div>

  <div class="info">
    <strong>Uploaded:</strong> <%= time_ago_in_words @video.created_at %> ago<br />
    <strong>By:</strong> <%= @video.user.full_name %>
  </div>

  <div class="description">
    <strong>Description:</strong><%= @video.description %>
  </div>

  <% if @video.converting? -%>
    <div class="alert">Video is still converting, please be patient</div>
  <% elsif @video.error? -%>
    <div class="alert alert-error">There was an error while converting your video</div>
  <% elsif @video.complete? -%>
    <div class="video-js-box">
      <video class="video-js" width="640" height="360"> 
        <source src="<%= @video.encoded_file_name %>" type="video/mp4" />

        <object class="vjs-flash-fallback" width="640" height="360" type="application/x-shockwave-flash" data="http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf">
          <param name="movie" value="http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf" />
          <param name="allowfullscreen" value="true" />
          <param name="flashvars" value='config={"playlist":["<%= @video.encoded_file_name %>", {"url": "<%= @video.encoded_file_name %>", "autoPlay": false, "autoBuffering": true}]}' />
        </object>
      </video>
    </div>
  <% end -%>
<% end %>

<div id="reviews">
  <h2>Video Reviews</h2>
  <%= render @video.reviews %>

  <%= simple_form_for @video.reviews.new, url: admin_video_reviews_path(@video), html: { multipart: true, class: 'form-vertical' } do |f| %>
    <fieldset>
      <legend>Add a review</legend>
      <%= f.input :description, input_html: { rows: 3 } %>
      <%= f.input :pdf, as: :file, label: 'Attach a PDF', required: false %>
    </fieldset>

    <div class="form-actions">
      <%= f.button :submit, 'Create review', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>